

services:
  tsst-server:
    build: .
    image: tsst-server:latest
    container_name: tsst_server
    restart: always
    network_mode: "host" # Crucial for SRT/UDP port allocations without heavy iptables
    devices:
      - /dev/dri:/dev/dri # Pasa la GPU de Intel (UHD 630) al contenedor
    volumes:
      - tsst_data:/usr/src/app/data
      - /media:/media:shared # :shared Propaga los montajes USB en tiempo real desde el Linux al Docker
    environment:
      - NODE_ENV=production

volumes:
  tsst_data:
